#Create a Deployment by using the SbServiceOne image pushed to Docker Hub
#Use containerPort 8761

apiVersion: apps/v1
---
#Create the Service of type LoadBalancer and use the above created Deployment as selector
#Use port 8081

apiVersion: v1
